export const jobs = {
    "job1": {
        "Company": "Mobile First Corp",
        "Role": "React Native Developer",
        "Location": "Remote",
        "Time": "Full-time",
        "Salary": "$130,000 - $175,000",
        "Status": "pending",
        "Description": "Build cross-platform mobile applications using React Native. Work on products used by millions of users worldwide.",
    },
    "job2": {
        "Company": "Webflow Agency",
        "Role": "Web Design and Developer",
        "Location": "Los Angeles, CA",
        "Time": "Part-time",
        "Salary": "$80,000 - $120,000",
        "Status": "pending",
        "Description": "Create stunning web experiences for high-profile clients. Must have portfolio and experience with modern web design trends.",
    },
    "job3": {
        "Company": "DataViz Solutions",
        "Role": "Data Visualization Specialists",
        "Location": "Boston, MA",
        "Time": "Full-time",
        "Salary": "$125,000 - $165,000",
        "Status": "pending",
        "Description": "Transform complex data into compelling visualizations. Required skills: D3.js, React, and strong analytical thinking.",
    },
    "job4": {
        "Company": "Webflow Agency",
        "Role": "Web Design and Developer",
        "Location": "Los Angeles, CA",
        "Time": "Part-time",
        "Salary": "$80,000 - $120,000",
        "Status": "pending",
        "Description": "Create stunning web experiences for high-profile clients. Must have portfolio and experience with modern web design trends.",
    },
    "job5": {
        "Company": "CloudFirst Inc",
        "Role": "Backend Developer",
        "Location": "Seattle, WA",
        "Time": "Full-time",
        "Salary": "$140,000 - $190,000",
        "Status": "pending",
        "Description": "Design and maintain scalable backend systems using Python and AWS. Work with modern DevOps practices and cloud infrastructure.",
    },
    "job6": {
        "Company": "Innovation Lab",
        "Role": "UI/UX Enginner",
        "Location": "Austin, TX",
        "Time": "Full-time",
        "Salary": "$110,000 - $150,000",
        "Status": "pending",
        "Description": "Create beautiful and functional user interfaces for our suite of products. Strong design skills and frontend development expertise required.",
    },
    "job7": {
        "Company": "MegaCorp Solution",
        "Role": "JavaScript Developer",
        "Location": "New York, NY",
        "Time": "Full-time",
        "Salary": "$130,000 - $170,000",
        "Status": "pending",
        "Description": "Build enterprise applications with JavaScript and modern frameworks. We offer competitive compensation, health insurance, and professional development opportunities.",
    },
    "job8": {
        "Company": "StartupXYZ",
        "Role": "Full Stack Engineer",
        "Location": "Remote",
        "Time": "Full-time",
        "Salary": "$120,000 - $160,000",
        "Status": "pending",
        "Description": "Join our fast-growing startup and work on our core platform. Experience with Node.js and React required. Great benefits and equity package included.",
    },
    "job9": {
        "Company": "Techcorp Industries",
        "Role": "Senior Frontend Developer",
        "Location": "San Fransisco, CA",
        "Time": "Full-time",
        "Salary": "$130,000 - $175,000",
        "Status": "pending",
        "Description": "We are looking for an experienced Frontend Developer to build scalable web applications using React and TypeScript. You will work with a talented team on cutting-edge projects.",
    },
    "job10": {
        "Company": "StartupXYZ",
        "Role": "Full Stack Engineer",
        "Location": "Remote",
        "Time": "Full-time",
        "Salary": "$120,000 - $160,000",
        "Status": "pending",
        "Description": "Join our fast-growing startup and work on our core platform. Experience with Node.js and React required. Great benefits and equity package included.",
    },
}